set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

if(NOT DEFINED ENV{RECAMERA_SYSROOT} OR "$ENV{RECAMERA_SYSROOT}" STREQUAL "")
    message(FATAL_ERROR "请设置 RECAMERA_SYSROOT=/absolute/path/to/recamera-pro-sysroot")
endif()
set(CMAKE_SYSROOT "$ENV{RECAMERA_SYSROOT}")

if(DEFINED ENV{RECAMERA_CROSS_PREFIX} AND NOT "$ENV{RECAMERA_CROSS_PREFIX}" STREQUAL "")
    set(_prefix "$ENV{RECAMERA_CROSS_PREFIX}")
else()
    set(_prefix "aarch64-linux-gnu-")
endif()
set(CMAKE_C_COMPILER "${_prefix}gcc")
set(CMAKE_CXX_COMPILER "${_prefix}g++")

set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

